In [118]:
import numpy as np
import pandas as pd

In [119]:
file=r"E:\Jaison\Cource Meterials\Python\ML\Data\Existing Base.csv"
bd=pd.read_csv(file)
bd.head()

REF_NO children age_band                status        occupation  \
0       1     Zero    51-55               Partner     Manual Worker   
1       2     Zero    55-60  Single/Never Married           Retired   
2       3     Zero    26-30  Single/Never Married      Professional   
3       5     Zero    18-21  Single/Never Married      Professional   
4       6     Zero    45-50               Partner  Business Manager   

  occupation_partner home_status      family_income self_employed  \
0  Secretarial/Admin    Own Home  <17,500, >=15,000            No   
1            Retired    Own Home  <27,500, >=25,000            No   
2              Other    Own Home  <30,000, >=27,500           Yes   
3      Manual Worker    Own Home  <15,000, >=12,500            No   
4            Unknown    Own Home  <30,000, >=27,500            No   

  self_employed_partner        ...          Investment Tax Saving Bond  \
0                    No        ...                               19.99   
1                    No        ...                                0.00   
2                    No        ...                                0.00   
3                    No        ...                                0.00   
4                    No        ...                                0.00   

  Home Loan Online Purchase Amount Revenue Grid  gender         region  \
0      0.00                   0.00            1  Female          Wales   
1      0.00                   0.00            2  Female     North West   
2      3.49                   0.00            2    Male          North   
3      0.00                   0.00            2  Female  West Midlands   
4     45.91                  25.98            2  Female       Scotland   

   Investment in Commudity  Investment in Equity  Investment in Derivative  \
0                    74.67                 18.66                     32.32   
1                    20.19                  0.00                      4.33   
2                    98.06                 31.07                     80.96   
3                     4.10                 14.15                     17.57   
4                    70.16                 55.86                     80.44   

   Portfolio Balance  
0              89.43  
1              22.78  
2             171.78  
3             -41.70  
4             235.02  

[5 rows x 32 columns]

In [120]:
list(zip(bd.columns,bd.dtypes,bd.nunique()))

[('REF_NO', dtype('int64'), 10155),
 ('children', dtype('O'), 5),
 ('age_band', dtype('O'), 13),
 ('status', dtype('O'), 5),
 ('occupation', dtype('O'), 9),
 ('occupation_partner', dtype('O'), 9),
 ('home_status', dtype('O'), 5),
 ('family_income', dtype('O'), 13),
 ('self_employed', dtype('O'), 2),
 ('self_employed_partner', dtype('O'), 2),
 ('year_last_moved', dtype('int64'), 95),
 ('TVarea', dtype('O'), 14),
 ('post_code', dtype('O'), 10040),
 ('post_area', dtype('O'), 2039),
 ('Average Credit Card Transaction', dtype('float64'), 1411),
 ('Balance Transfer', dtype('float64'), 2183),
 ('Term Deposit', dtype('float64'), 1419),
 ('Life Insurance', dtype('float64'), 3111),
 ('Medical Insurance', dtype('float64'), 1589),
 ('Average A/C Balance', dtype('float64'), 2223),
 ('Personal Loan', dtype('float64'), 1760),
 ('Investment in Mutual Fund', dtype('float64'), 2470),
 ('Investment Tax Saving Bond', dtype('float64'), 832),
 ('Home Loan', dtype('float64'), 884),
 ('Online Purchase Amount'

In [126]:
bd['children'].value_counts()

0    6208
1    1848
2    1607
3     473
4      19
Name: children, dtype: int64

In [127]:
bd['children'].dtype

dtype('int64')

In [123]:
bd['children']=np.where(bd['children'].str[:4]=='Zero',0,bd['children'])

In [124]:
bd['children']=np.where(bd['children'].str[:2]=='4+',4,bd['children'])

In [125]:
bd['children']=pd.to_numeric(bd['children'],errors='coerce')

In [131]:
bd['age'].value_counts()

47.5    1359
38.0    1134
43.0    1112
33.0    1061
53.0    1052
57.5    1047
28.0     927
63.0     881
67.5     598
23.5     456
19.5      63
Name: age, dtype: int64

In [128]:
bd['age_band']=np.where(bd['age_band'].str[:3]=='71+',71,bd['age_band'])

In [129]:
bd['age_band']=bd['age_band'].str.replace('Unknown','0')

In [130]:
k=bd['age_band'].str.split('-',expand=True).astype(float)
bd['age']=0.5*(k[0]+k[1])
del bd['age_band']

In [132]:
bd.head()

REF_NO  children                status        occupation  \
0       1         0               Partner     Manual Worker   
1       2         0  Single/Never Married           Retired   
2       3         0  Single/Never Married      Professional   
3       5         0  Single/Never Married      Professional   
4       6         0               Partner  Business Manager   

  occupation_partner home_status      family_income self_employed  \
0  Secretarial/Admin    Own Home  <17,500, >=15,000            No   
1            Retired    Own Home  <27,500, >=25,000            No   
2              Other    Own Home  <30,000, >=27,500           Yes   
3      Manual Worker    Own Home  <15,000, >=12,500            No   
4            Unknown    Own Home  <30,000, >=27,500            No   

  self_employed_partner  year_last_moved  ...  Home Loan  \
0                    No             1972  ...       0.00   
1                    No             1998  ...       0.00   
2                    No             1996  ...       3.49   
3                    No             1997  ...       0.00   
4                    No             1995  ...      45.91   

  Online Purchase Amount Revenue Grid  gender         region  \
0                   0.00            1  Female          Wales   
1                   0.00            2  Female     North West   
2                   0.00            2    Male          North   
3                   0.00            2  Female  West Midlands   
4                  25.98            2  Female       Scotland   

   Investment in Commudity  Investment in Equity  Investment in Derivative  \
0                    74.67                 18.66                     32.32   
1                    20.19                  0.00                      4.33   
2                    98.06                 31.07                     80.96   
3                     4.10                 14.15                     17.57   
4                    70.16                 55.86                     80.44   

   Portfolio Balance   age  
0              89.43  53.0  
1              22.78  57.5  
2             171.78  28.0  
3             -41.70  19.5  
4             235.02  47.5  

[5 rows x 32 columns]

In [140]:
bd['family_income'].value_counts()

35000            2517
<27500>=25000    1227
<30000>=27500     994
<25000>=22500     833
<20000>=17500     683
<12500>=10000     677
<17500>=15000     634
<15000>=12500     629
<22500>=20000     590
<10000>=8000      563
<8000>=4000       402
<4000             278
1                 128
Name: family_income, dtype: int64

In [73]:
bd['family_income']=np.where(bd['family_income'].str[:7]==0,1,bd['family_income'])

In [136]:
bd['family_income']=bd['family_income'].str.replace(',','')

In [134]:
bd['family_income']=bd['family_income'].str.replace('Unknown','1')

In [137]:
bd['family_income']=bd['family_income'].str.replace(' ','')

In [78]:
bd['family_income']=bd['family_income'].str.replace('>=35000','35000')

In [145]:
bd['family_income']=bd['family_income'].str.replace('<30000>=27500','28750')

In [147]:
bd['family_income']=bd['family_income'].str.replace('<25000>=22500','23750')

In [149]:
bd['family_income']=bd['family_income'].str.replace('<20000>=17500','18750')

In [ ]:
bd['family_income']=bd['family_income'].str.replace('<12500>=10000','23750')

In [151]:
bd['family_income']=bd['family_income'].str.replace('<12500>=10000','11250')

In [153]:
bd['family_income']=bd['family_income'].str.replace('<17500>=15000','16250')

In [155]:
bd['family_income']=bd['family_income'].str.replace('<15000>=12500','13750')

In [157]:
bd['family_income']=bd['family_income'].str.replace('<22500>=20000','21250')

In [159]:
bd['family_income']=bd['family_income'].str.replace('<10000>=8000','9000')

In [163]:
bd['family_income']=bd['family_income'].str.replace('<8000>=4000','6000')

In [164]:
bd['family_income']=bd['family_income'].str.replace('<4000','4000')

In [167]:
bd['family_income'].value_counts()

35000    2517
26250    1227
28750     994
23750     833
18750     683
11250     677
16250     634
13750     629
21250     590
9000      563
6000      402
4000      278
1         128
Name: family_income, dtype: int64

In [168]:
bd.drop(['REF_NO','post_code','post_area'],axis=1,inplace=True)

In [166]:
bd['family_income']=pd.to_numeric(bd['family_income'],errors='coerce')

In [181]:
bd['family_income'].value_counts()

35000    2517
26250    1227
28750     994
23750     833
18750     683
11250     677
16250     634
13750     629
21250     590
9000      563
6000      402
4000      278
1         128
Name: family_income, dtype: int64

In [171]:
bd['Revenue Grid'].value_counts()

0    9069
1    1086
Name: Revenue Grid, dtype: int64

In [170]:
bd['Revenue Grid']=bd['Revenue Grid'].replace(2,0)

In [172]:
cat_var=bd.select_dtypes(['object']).columns
cat_var

Index(['status', 'occupation', 'occupation_partner', 'home_status',
       'self_employed', 'self_employed_partner', 'TVarea', 'gender', 'region'],
      dtype='object')

In [173]:
for col in cat_var:
    dummy=pd.get_dummies(bd[col],drop_first=True,prefix=col)
    bd=pd.concat([bd,dummy],axis=1)
    del bd[col]
    print(col)
del dummy
bd.shape

status
occupation
occupation_partner
home_status
self_employed
self_employed_partner
TVarea
gender
region


(10155, 73)

In [174]:
bd['children'].value_counts()

0    6208
1    1848
2    1607
3     473
4      19
Name: children, dtype: int64

In [184]:
for col in bd.columns:
    if (bd[col].isnull().sum()>0):
        print(col)

In [183]:
for col in bd.columns:
    if (bd[col].isnull().sum()>0):
        bd.loc[bd[col].isnull(),col]=0.01

In [185]:
bd.columns

Index(['children', 'family_income', 'year_last_moved',
       'Average Credit Card Transaction', 'Balance Transfer', 'Term Deposit',
       'Life Insurance', 'Medical Insurance', 'Average A/C Balance',
       'Personal Loan', 'Investment in Mutual Fund',
       'Investment Tax Saving Bond', 'Home Loan', 'Online Purchase Amount',
       'Revenue Grid', 'Investment in Commudity', 'Investment in Equity',
       'Investment in Derivative', 'Portfolio Balance', 'age',
       'status_Partner', 'status_Single/Never Married', 'status_Unknown',
       'status_Widowed', 'occupation_Housewife', 'occupation_Manual Worker',
       'occupation_Other', 'occupation_Professional', 'occupation_Retired',
       'occupation_Secretarial/Admin', 'occupation_Student',
       'occupation_Unknown', 'occupation_partner_Housewife',
       'occupation_partner_Manual Worker', 'occupation_partner_Other',
       'occupation_partner_Professional', 'occupation_partner_Retired',
       'occupation_partner_Secretarial/A

In [186]:
bd.shape

(10155, 73)

In [187]:
from sklearn.model_selection import train_test_split

In [188]:
bd_train,bd_test=train_test_split(bd,test_size=0.2,random_state=2)

In [189]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

In [190]:
logr=LogisticRegression(class_weight='balanced')

In [194]:
x_train=bd_train.drop(['Revenue Grid'],axis=1)
y_train=bd_train['Revenue Grid']
x_test=bd_test.drop(['Revenue Grid'],axis=1)
y_test=bd_test["Revenue Grid"]

In [196]:
logr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [197]:
logr.predict(x_test)

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [198]:
logr.predict_proba(x_test)

array([[0.97351629, 0.02648371],
       [0.93985142, 0.06014858],
       [0.92628942, 0.07371058],
       ...,
       [0.11758804, 0.88241196],
       [0.16470626, 0.83529374],
       [0.93744239, 0.06255761]])

In [199]:
logr.classes_

array([0, 1], dtype=int64)

In [200]:
 predicted_probs=logr.predict_proba(x_test)[:,1]

In [201]:
predicted_probs

array([0.02648371, 0.06014858, 0.07371058, ..., 0.88241196, 0.83529374,
       0.06255761])

In [202]:
roc_auc_score(y_test,predicted_probs)

0.9477601984346589

In [284]:
cutoffs=np.linspace(0.424,0.426,500)
cutoffs

array([0.424     , 0.42400401, 0.42400802, 0.42401202, 0.42401603,
       0.42402004, 0.42402405, 0.42402806, 0.42403206, 0.42403607,
       0.42404008, 0.42404409, 0.4240481 , 0.4240521 , 0.42405611,
       0.42406012, 0.42406413, 0.42406814, 0.42407214, 0.42407615,
       0.42408016, 0.42408417, 0.42408818, 0.42409218, 0.42409619,
       0.4241002 , 0.42410421, 0.42410822, 0.42411222, 0.42411623,
       0.42412024, 0.42412425, 0.42412826, 0.42413226, 0.42413627,
       0.42414028, 0.42414429, 0.4241483 , 0.4241523 , 0.42415631,
       0.42416032, 0.42416433, 0.42416834, 0.42417234, 0.42417635,
       0.42418036, 0.42418437, 0.42418838, 0.42419238, 0.42419639,
       0.4242004 , 0.42420441, 0.42420842, 0.42421242, 0.42421643,
       0.42422044, 0.42422445, 0.42422846, 0.42423246, 0.42423647,
       0.42424048, 0.42424449, 0.4242485 , 0.42425251, 0.42425651,
       0.42426052, 0.42426453, 0.42426854, 0.42427255, 0.42427655,
       0.42428056, 0.42428457, 0.42428858, 0.42429259, 0.42429

In [285]:
train_score=logr.predict_proba(x_train)[:,1]
real=y_train

In [286]:
KS_all=[]

for cutoff in cutoffs:
    
    predicted=(train_score>cutoff).astype(int)
    
    TP=((predicted==1) & (real==1)).sum()
    TN=((predicted==0) & (real==0)).sum()
    FP=((predicted==1) & (real==0)).sum()
    FN=((predicted==0) & (real==1)).sum()
    
    P=TP+FN
    N=TN+FP
    KS=(TP/P)-(FP/N)
    KS_all.append(KS)

In [287]:
cutoffs[KS_all==max(KS_all)]

array([0.42457315, 0.42457715, 0.42458116, 0.42458517, 0.42458918,
       0.42459319, 0.42459719, 0.4246012 , 0.42460521, 0.42460922,
       0.42461323, 0.42461723, 0.42462124, 0.42462525, 0.42462926,
       0.42463327, 0.42463727, 0.42464128, 0.42464529, 0.4246493 ,
       0.42465331, 0.42465731, 0.42466132, 0.42466533, 0.42466934,
       0.42467335, 0.42467735, 0.42468136, 0.42468537, 0.42468938,
       0.42469339, 0.42469739, 0.4247014 , 0.42470541, 0.42470942,
       0.42471343, 0.42471743, 0.42472144, 0.42472545, 0.42472946,
       0.42473347, 0.42473747, 0.42474148, 0.42474549, 0.4247495 ,
       0.42475351, 0.42475752, 0.42476152, 0.42476553, 0.42476954,
       0.42477355, 0.42477756, 0.42478156, 0.42478557, 0.42478958,
       0.42479359, 0.4247976 , 0.4248016 , 0.42480561, 0.42480962,
       0.42481363, 0.42481764, 0.42482164, 0.42482565, 0.42482966,
       0.42483367, 0.42483768, 0.42484168, 0.42484569, 0.4248497 ,
       0.42485371, 0.42485772, 0.42486172, 0.42486573, 0.42486

In [288]:
list(zip(x_train.columns,logr.coef_[0]))

[('children', -0.010324629204762575),
 ('family_income', 4.814922892848107e-06),
 ('year_last_moved', -0.000281548485429019),
 ('Average Credit Card Transaction', 0.022673922651934304),
 ('Balance Transfer', -0.005877311500203519),
 ('Term Deposit', -0.019230409767173752),
 ('Life Insurance', 0.007839554816935834),
 ('Medical Insurance', -0.01790786908679223),
 ('Average A/C Balance', -0.00897550550529398),
 ('Personal Loan', -0.0391897495335612),
 ('Investment in Mutual Fund', -0.007331343855521319),
 ('Investment Tax Saving Bond', 0.08460992480653223),
 ('Home Loan', -0.08210593279242014),
 ('Online Purchase Amount', 0.056456642927178814),
 ('Investment in Commudity', 0.003185228528989444),
 ('Investment in Equity', 0.004511522766209585),
 ('Investment in Derivative', 0.03906065476324745),
 ('Portfolio Balance', -0.00023217989177703658),
 ('age', -0.005474649878799067),
 ('status_Partner', 0.13910163100605255),
 ('status_Single/Never Married', -0.12635750095008508),
 ('status_Unknown